### ISSUE TITLE
TLSv1 support drop breaks addon on Kodi for Android

### ISSUE THREAD

**Issue by harlekinrains** [jimporter/giantbomb-kodi#6]
See http://www.giantbomb.com/forums/bug-reporting-33/tlsv1-support-dropped-1784805/#3

I started to receive connection errors 100% of the time as well - on Kodi running on an Amazon Fire TV Stick (which is based on Android 4.2) - so the entire Addon started to become useless for me.

Please respond if there is anything you could do to prevent this from happening.

**Comment by jimporter** [comment]
It sounds like this issue will go away once Fire OS 5.0 is out, which looks to be "real soon now". I'm debating if it's worth releasing a new version of the add-on to fix this, or if it would make more sense to wait for Fire OS 5.0.

In the meantime, you could just patch the add-on so it doesn't use HTTPS.

**Comment by harlekinrains** [comment]
This is a very "in scene" argument, but Fire OS 5.0 (Android 5.0) will limit the adb connections to the device to "one active one" - which may or may not have to be triggered to be opened after the initial boot by disabling/enabling the ADB debug switch -

On a device already as artificially limited as the Fire TV this will break several of my workflows - in short, I'll not be sprinting for the update. In fact, I am already blocking the update servers as I write this.

I've already looked into the py file, but have found no instances, where https would have been requested by the addon itself - so any help would be appreciated -

If you can point me to how to modify the addon to not listen to http request, I'll do so myself -

- and if you'd consider to "make it an option" regardless - keeping some of the fringe cases (users like me, users on import Android boxes that wont get newer OS releases) in mind, I'd be grateful as well.

Have some sort of economic rational in mind regarding how much time it will take for you to do so - but be assured, that Android 5.0 will not be the solution for all people out there.

:)

Thank you for the reply,

harlekin aka Philipp Ganster  


Am Samstag, 24. Oktober 2015 um 22:57 schrieb Jim Porter:

**Comment by jimporter** [comment]
You just need to change this line: https://github.com/jimporter/giantbomb-kodi/blob/master/plugin.video.giantbomb/resources/lib/giantbomb.py#L31

Once you do that, you can just run `make package` from a command line (assuming you're on a system with Make), or zip the plugin.video.giantbomb folder. Then put the file on your device however you normally do that.

It's not hard to fix this in the add-on, but the main problem is figuring out how user-friendly I want to be. If only a few people actually need the feature, I could just make it an option that needs to be explicitly set, but if lots of people are likely to run into this, I'd need a way to detect the problem an automatically fall back to HTTP.

**Comment by harlekinrains** [comment]
Thanks, i'll look into it. If it works, its entirely fine with me. Decide
the rest depending on future feedback you get on this issue. :)
Am 24.10.2015 23:59 schrieb "Jim Porter" <notifications@github.com>:

**Comment by harlekinrains** [comment]
After the change and rebooting Kodi I first got resolving errors upon trying to play any video link (browsing the categories worked fine), which vanished after a second reboot. (Strange.) Lets just say it works. Now. ;)

Thank you for pointing me in the right direction. I missed the giantbomb.py file on my first look around. :)  


Am Sonntag, 25. Oktober 2015 um 05:32 schrieb harlekin:

**Comment by jimporter** [comment]
I released v4.3.0 which has an advanced option to turn off HTTPS.

**Comment by harlekinrains** [comment]
Version v4.3.0 still fails to connect on Android 4.2 with TLS disabled in the options.

Tried with reboots - heres a log:

http://pastebin.com/fYFZ8hd0  


Am Sonntag, 25. Oktober 2015 um 21:17 schrieb Jim Porter:

**Comment by jimporter** [comment]
Fixed in 4.3.1

**Comment by harlekinrains** [comment]
Additional information to TLS disabled in v4.3.0 still broken (same connection errors):

I am using Kodi version 14.2 and also tried it deleting the settings file from user data - same error, then tried to set the default value in the settings.xml to false and hit a "default settings" in Kodi (checkbox remained unticked at all times), and it still failed. Enabled/Disabled a few times - still failed. Regardless of the account being linked or not.  


Am Montag, 26. Oktober 2015 um 06:56 schrieb Philipp Ganster:

**Comment by harlekinrains** [comment]
Installed 4.3.1 - now the file listings and categories resolve - but now - take a breath - there is a bigger problem...

When 4.3.0 didnt work and I went back to 4.2.1 with the s from https deleted from the giantbomb.py (line 31) I saw the same error profile today already - but I swear it still worked yesterday...

This is what is happening now (in 4.2.1 as well as in 4.3.1), with TLS disabled in the settings, I can enter categories and the file listings appear - but when I try to play a video (premium or not), it fails - and it fails because the video link now is handed over to Kodi as https - as is visible in the logs:

http://pastebin.com/ySXFX7CJ

But now - there is the kicker, when I install the old Whiskeymedia addon (3.5.1) - it resolves and playes the videos perfectly.

I guess the question now is - can you but the video urls through a regex script within the plugin, that strips the s from the https video urls? Also - dont ask me what changed from yesterday.

Getting into the category listings always was the first - and up to yesterday the only - stumbling block (from a user experience perspective), now there is this new one.  


Am Montag, 26. Oktober 2015 um 07:26 schrieb Jim Porter:

**Comment by jimporter** [comment]
Arguably, that's a bug on Giant Bomb's end, since the URL they provide me for an individual video always uses HTTPS even if I talk to the API via HTTP. I'll see if I can figure out a better way to handle this.

**Comment by jimporter** [comment]
@harlekinrains Try the latest version on master. If it actually works for you, I'll release it (as 5.0, since I had to break compatibility with the old URL format).

**Comment by harlekinrains** [comment]
Im on it, feedback in five minutes.
Am 27.10.2015 23:24 schrieb "Jim Porter" <notifications@github.com>:

**Comment by harlekinrains** [comment]
It works. On premium and non premium content. Categories work. Quality
selection works (allthough High also resolves 720p (havent looked at the
bitrate)). Congratulations, youve conquered the problem. Thank you very
much for putting the time into it.
Am 27.10.2015 23:27 schrieb "Jim Porter" <notifications@github.com>:

**Comment by jimporter** [comment]
Ok, cool. I'm going to add a couple extra bits for 5.0 and then release it for reals.
